### PR TITLE
Ereed

### PR DESCRIPTION
**Pull request by ericreed**
I added a title to the plot in code2.r.

### CODE REVIEW

**Comment by dkulp2** [comment]
Hi.  A couple problems here.  First, the .gitignore continues to be wonky.  It shouldn't have any of the conflict marks in it, but each time you submit a branch you have conflicts marked with <<< and >>> etc that need to be removed.
Second, I think there's a misunderstanding about the .Rmdp file.  It looks like you renamed it to .Rmd and removed the "code0.r"/ tags used by the pre-processor.  
The idea is for there to always be an .Rmdp file.  Then run "make" to create the .Rmd (which isn't in the repo).  And then run knitr.  There shouldn't be any read_chunk because that was causing errors.  Changes like adding the title should be made to the .Rmdp file.

**Comment by ericreed** [comment]
Hi Dave,

I'm not sure why my .rmdp didn't push on my last push.  It should be there now.  I think we are one the same page as far as editting .rmdp file -> make -> compile. rmd

**Comment by dkulp2** [comment]
OK.  I see it all looks fine now.  But .Rmd shouldn't be in the repo.

**Comment by ericreed** [comment]
Cool I'll take it out.

**Comment by dkulp2** [comment]
Thanks.  I'm going to fix your .gitignore -- hopefully once and for all.

**Pull request merged**
